
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2020.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2025 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xintc.h"


extern void XNullHandler (void *);

/*
* The configuration table for devices
*/

XIntc_Config XIntc_ConfigTable[] =
{
	{
		XPAR_AXI_INTC_BAREMETAL_DEVICE_ID,
		XPAR_AXI_INTC_BAREMETAL_BASEADDR,
		XPAR_AXI_INTC_BAREMETAL_KIND_OF_INTR,
		XPAR_AXI_INTC_BAREMETAL_HAS_FAST,
		XPAR_AXI_INTC_BAREMETAL_IVAR_RESET_VALUE,
		XPAR_AXI_INTC_BAREMETAL_NUM_INTR_INPUTS,
		XPAR_AXI_INTC_BAREMETAL_ADDR_WIDTH,
		XIN_SVC_SGL_ISR_OPTION,
		XPAR_AXI_INTC_BAREMETAL_TYPE,
		{
			{
				XNullHandler,
				(void *) XNULL
			},
			{
				XNullHandler,
				(void *) XNULL
			},
			{
				XNullHandler,
				(void *) XNULL
			},
			{
				XNullHandler,
				(void *) XNULL
			},
			{
				XNullHandler,
				(void *) XNULL
			},
			{
				XNullHandler,
				(void *) XNULL
			},
			{
				XNullHandler,
				(void *) XNULL
			},
			{
				XNullHandler,
				(void *) XNULL
			},
			{
				XNullHandler,
				(void *) XNULL
			},
			{
				XNullHandler,
				(void *) XNULL
			},
			{
				XNullHandler,
				(void *) XNULL
			},
			{
				XNullHandler,
				(void *) XNULL
			}
		},
		XPAR_AXI_INTC_BAREMETAL_NUM_SW_INTR
	}
};

