#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : system.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Mon Mar 24 10:41:18 +0800 2025
# SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved. 
#
# usage: system.sh [-help]
# usage: system.sh [-lib_map_path]
# usage: system.sh [-noclean_files]
# usage: system.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'system.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xpm axi_infrastructure_v1_1_0 axi_vip_v1_1_8 processing_system7_vip_v1_0_10 xil_defaultlib lib_cdc_v1_0_2 lib_pkg_v1_0_2 fifo_generator_v13_2_5 lib_fifo_v1_0_14 blk_mem_gen_v8_4_4 lib_bmg_v1_0_13 lib_srl_fifo_v1_0_2 axi_datamover_v5_1_24 axi_vdma_v6_3_10 axi_lite_ipif_v3_0_4 v_tc_v6_2_1 v_tc_v6_1_13 v_vid_in_axi4s_v4_0_9 v_axi4s_vid_out_v4_0_11 interrupt_control_v3_1_4 axi_gpio_v2_0_24 xlconstant_v1_1_7 proc_sys_reset_v5_0_13 smartconnect_v1_0 axi_register_slice_v2_1_22 xlconcat_v2_1_4 generic_baseblocks_v2_1_0 axi_data_fifo_v2_1_21 axi_crossbar_v2_1_23 axi_sg_v4_1_13 axi_dma_v7_1_23 axis_infrastructure_v1_1_0 axis_data_fifo_v2_0_4 axi_bram_ctrl_v4_1_4 axi_uartlite_v2_0_26 util_vector_logic_v2_0_1 axi_iic_v2_0_25 axi_protocol_converter_v2_1_22)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "system.sh - Script generated by export_simulation (Vivado v2020.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"E:/vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "E:/vivado/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "E:/vivado/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "E:/vivado/Vivado/2020.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "E:/vivado/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "E:/vivado/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "E:/vivado/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "E:/vivado/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "E:/vivado/Vivado/2020.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "E:/vivado/Vivado/2020.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"E:/vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "E:/vivado/Vivado/2020.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "E:/vivado/Vivado/2020.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "E:/vivado/Vivado/2020.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "E:/vivado/Vivado/2020.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"E:/vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_8 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"E:/vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/94c3/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work processing_system7_vip_v1_0_10 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"E:/vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/34f8/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"E:/vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_processing_system7_0_0/sim/system_processing_system7_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"E:/vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/276e/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_5 $vhdlan_opts \
    "$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/276e/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"E:/vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/276e/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_fifo_v1_0_14 $vhdlan_opts \
    "$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/a5cb/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work blk_mem_gen_v8_4_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"E:/vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/2985/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_bmg_v1_0_13 $vhdlan_opts \
    "$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/af67/hdl/lib_bmg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_datamover_v5_1_24 $vhdlan_opts \
    "$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/4ab6/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_vdma_v6_3_10 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"E:/vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/7860/hdl/axi_vdma_v6_3_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_vdma_v6_3_10 $vhdlan_opts \
    "$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/7860/hdl/axi_vdma_v6_3_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_axi_vdma_0_0/sim/system_axi_vdma_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work v_tc_v6_2_1 $vhdlan_opts \
    "$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/cd2e/hdl/v_tc_v6_2_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_v_tc_0_0/sim/system_v_tc_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work v_tc_v6_1_13 $vhdlan_opts \
    "$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/b92e/hdl/v_tc_v6_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work v_vid_in_axi4s_v4_0_9 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"E:/vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/b2aa/hdl/v_vid_in_axi4s_v4_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work v_axi4s_vid_out_v4_0_11 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"E:/vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/1a1e/hdl/v_axi4s_vid_out_v4_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"E:/vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_v_axi4s_vid_out_0_0/sim/system_v_axi4s_vid_out_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work interrupt_control_v3_1_4 $vhdlan_opts \
    "$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/a040/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_gpio_v2_0_24 $vhdlan_opts \
    "$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/4318/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_axi_gpio_0_0/sim/system_axi_gpio_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlconstant_v1_1_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"E:/vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/fcfc/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"E:/vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_0/bd_0/ip/ip_0/sim/bd_44e3_one_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_0/bd_0/ip/ip_1/sim/bd_44e3_psr_aclk_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"E:/vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/25b7/hdl/sc_util_v1_0_vl_rfs.sv" \
    "$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/c012/hdl/sc_switchboard_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"E:/vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_0/bd_0/ip/ip_2/sim/bd_44e3_arsw_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_0/bd_0/ip/ip_3/sim/bd_44e3_rsw_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_0/bd_0/ip/ip_4/sim/bd_44e3_awsw_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_0/bd_0/ip/ip_5/sim/bd_44e3_wsw_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_0/bd_0/ip/ip_6/sim/bd_44e3_bsw_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"E:/vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/ea34/hdl/sc_mmu_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"E:/vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_0/bd_0/ip/ip_7/sim/bd_44e3_s00mmu_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"E:/vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/4fd2/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"E:/vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_0/bd_0/ip/ip_8/sim/bd_44e3_s00tr_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"E:/vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/8047/hdl/sc_si_converter_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"E:/vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_0/bd_0/ip/ip_9/sim/bd_44e3_s00sic_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"E:/vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/b89e/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"E:/vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_0/bd_0/ip/ip_10/sim/bd_44e3_s00a2s_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"E:/vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/896c/hdl/sc_node_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"E:/vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_0/bd_0/ip/ip_11/sim/bd_44e3_sarn_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_0/bd_0/ip/ip_12/sim/bd_44e3_srn_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_0/bd_0/ip/ip_13/sim/bd_44e3_s01mmu_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_0/bd_0/ip/ip_14/sim/bd_44e3_s01tr_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_0/bd_0/ip/ip_15/sim/bd_44e3_s01sic_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_0/bd_0/ip/ip_16/sim/bd_44e3_s01a2s_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_0/bd_0/ip/ip_17/sim/bd_44e3_sawn_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_0/bd_0/ip/ip_18/sim/bd_44e3_swn_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_0/bd_0/ip/ip_19/sim/bd_44e3_sbn_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"E:/vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/7005/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"E:/vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_0/bd_0/ip/ip_20/sim/bd_44e3_m00s2a_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_0/bd_0/ip/ip_21/sim/bd_44e3_m00arn_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_0/bd_0/ip/ip_22/sim/bd_44e3_m00rn_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_0/bd_0/ip/ip_23/sim/bd_44e3_m00awn_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_0/bd_0/ip/ip_24/sim/bd_44e3_m00wn_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_0/bd_0/ip/ip_25/sim/bd_44e3_m00bn_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"E:/vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/7bd7/hdl/sc_exit_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"E:/vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_0/bd_0/ip/ip_26/sim/bd_44e3_m00e_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"E:/vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_0/bd_0/sim/bd_44e3.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_22 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"E:/vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/af2c/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"E:/vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_axi_smc_0/sim/system_axi_smc_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_rst_ps7_0_100M_0/sim/system_rst_ps7_0_100M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"E:/vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0_mmcm_pll_drp.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_clk_wiz_0_0/proc_common_v3_00_a/hdl/src/vhdl/system_clk_wiz_0_0_conv_funs_pkg.vhd" \
    "$ref_dir/../../../bd/system/ip/system_clk_wiz_0_0/proc_common_v3_00_a/hdl/src/vhdl/system_clk_wiz_0_0_proc_common_pkg.vhd" \
    "$ref_dir/../../../bd/system/ip/system_clk_wiz_0_0/proc_common_v3_00_a/hdl/src/vhdl/system_clk_wiz_0_0_ipif_pkg.vhd" \
    "$ref_dir/../../../bd/system/ip/system_clk_wiz_0_0/proc_common_v3_00_a/hdl/src/vhdl/system_clk_wiz_0_0_family_support.vhd" \
    "$ref_dir/../../../bd/system/ip/system_clk_wiz_0_0/proc_common_v3_00_a/hdl/src/vhdl/system_clk_wiz_0_0_family.vhd" \
    "$ref_dir/../../../bd/system/ip/system_clk_wiz_0_0/proc_common_v3_00_a/hdl/src/vhdl/system_clk_wiz_0_0_soft_reset.vhd" \
    "$ref_dir/../../../bd/system/ip/system_clk_wiz_0_0/proc_common_v3_00_a/hdl/src/vhdl/system_clk_wiz_0_0_pselect_f.vhd" \
    "$ref_dir/../../../bd/system/ip/system_clk_wiz_0_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/system_clk_wiz_0_0_address_decoder.vhd" \
    "$ref_dir/../../../bd/system/ip/system_clk_wiz_0_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/system_clk_wiz_0_0_slave_attachment.vhd" \
    "$ref_dir/../../../bd/system/ip/system_clk_wiz_0_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/system_clk_wiz_0_0_axi_lite_ipif.vhd" \
    "$ref_dir/../../../bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0_clk_wiz_drp.vhd" \
    "$ref_dir/../../../bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0_axi_clk_config.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"E:/vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0_clk_wiz.v" \
    "$ref_dir/../../../bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"E:/vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ipshared/154f/hdl/PWM_AXI.sv" \
    "$ref_dir/../../../bd/system/ipshared/154f/hdl/PWM_v2_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_PWM_0_0/sim/system_PWM_0_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"E:/vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ipshared/214f/src/rgb2lcd.v" \
    "$ref_dir/../../../bd/system/ip/system_rgb2lcd_0_1/sim/system_rgb2lcd_0_1.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconcat_v2_1_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"E:/vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/4b67/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"E:/vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_xlconcat_0_0/sim/system_xlconcat_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"E:/vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_21 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"E:/vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/54c0/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_23 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"E:/vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/bc0a/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"E:/vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_xbar_0/sim/system_xbar_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_sg_v4_1_13 $vhdlan_opts \
    "$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/4919/hdl/axi_sg_v4_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_dma_v7_1_23 $vhdlan_opts \
    "$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/89d8/hdl/axi_dma_v7_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_axi_dma_0_0/sim/system_axi_dma_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"E:/vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ipshared/dd64/ad7606_axis.v" \
    "$ref_dir/../../../bd/system/ipshared/dd64/ad7606_ser2par128bit.v" \
    "$ref_dir/../../../bd/system/ipshared/dd64/adc_whole.v" \
    "$ref_dir/../../../bd/system/ip/system_adc_whole_0_0/sim/system_adc_whole_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"E:/vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/8713/hdl/axis_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_data_fifo_v2_0_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"E:/vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/abd4/hdl/axis_data_fifo_v2_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"E:/vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_axis_data_fifo_0_0/sim/system_axis_data_fifo_0_0.v" \
    "$ref_dir/../../../bd/system/ipshared/24ef/dac_spi.v" \
    "$ref_dir/../../../bd/system/ipshared/24ef/dds_dac.v" \
    "$ref_dir/../../../bd/system/ipshared/24ef/dma_axis_s.v" \
    "$ref_dir/../../../bd/system/ipshared/24ef/dac_whole.v" \
    "$ref_dir/../../../bd/system/ip/system_dac_whole_0_1/sim/system_dac_whole_0_1.v" \
    "$ref_dir/../../../bd/system/ip/system_axis_data_fifo_1_1/sim/system_axis_data_fifo_1_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_proc_sys_reset_0_0/sim/system_proc_sys_reset_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"E:/vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_blk_mem_gen_0_0/sim/system_blk_mem_gen_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_bram_ctrl_v4_1_4 $vhdlan_opts \
    "$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/c9f0/hdl/axi_bram_ctrl_v4_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_axi_bram_ctrl_0_0/sim/system_axi_bram_ctrl_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"E:/vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ipshared/6fec/config2ser16bits.v" \
    "$ref_dir/../../../bd/system/ipshared/6fec/onoff_io.v" \
    "$ref_dir/../../../bd/system/ipshared/6fec/rd_from_serial8bit.v" \
    "$ref_dir/../../../bd/system/ipshared/6fec/onoff_config_axi.v" \
    "$ref_dir/../../../bd/system/ip/system_onoff_config_axi_0_0/sim/system_onoff_config_axi_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_rst_ps7_0_142M_0/sim/system_rst_ps7_0_142M_0.vhd" \
    "$ref_dir/../../../bd/system/ip/system_axi_gpio_0_1/sim/system_axi_gpio_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_uartlite_v2_0_26 $vhdlan_opts \
    "$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/5edb/hdl/axi_uartlite_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_axi_uartlite_0_0/sim/system_axi_uartlite_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work util_vector_logic_v2_0_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"E:/vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/3f90/hdl/util_vector_logic_v2_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"E:/vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_util_vector_logic_0_0/sim/system_util_vector_logic_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_iic_v2_0_25 $vhdlan_opts \
    "$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/1529/hdl/axi_iic_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_axi_iic_0_0/sim/system_axi_iic_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"E:/vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ipshared/2451/hdl/coder_v1_0_S00_AXI.v" \
    "$ref_dir/../../../bd/system/ipshared/2451/hdl/rotary_encoder.v" \
    "$ref_dir/../../../bd/system/ipshared/2451/hdl/coder_v1_0.v" \
    "$ref_dir/../../../bd/system/ip/system_coder_0_0/sim/system_coder_0_0.v" \
    "$ref_dir/../../../bd/system/ip/system_util_vector_logic_0_1/sim/system_util_vector_logic_0_1.v" \
    "$ref_dir/../../../bd/system/ipshared/934f/rgmii_rx.v" \
    "$ref_dir/../../../bd/system/ipshared/934f/rgmii_tx.v" \
    "$ref_dir/../../../bd/system/ipshared/934f/gmii_to_rgmii.v" \
    "$ref_dir/../../../bd/system/ip/system_gmii2rgmii_0_0/sim/system_gmii2rgmii_0_0.v" \
    "$ref_dir/../../../bd/system/ipshared/1858/power_pulse_in.v" \
    "$ref_dir/../../../bd/system/ipshared/1858/power_pulse_out.v" \
    "$ref_dir/../../../bd/system/ipshared/1858/power_pulse_v1_AXI.v" \
    "$ref_dir/../../../bd/system/ip/system_power_pulse_v1_AXI_0_0/sim/system_power_pulse_v1_AXI_0_0.v" \
    "$ref_dir/../../../bd/system/ip/system_tier2_xbar_0_0/sim/system_tier2_xbar_0_0.v" \
    "$ref_dir/../../../bd/system/ip/system_tier2_xbar_1_0/sim/system_tier2_xbar_1_0.v" \
    "$ref_dir/../../../bd/system/ip/system_tier2_xbar_2_0/sim/system_tier2_xbar_2_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_22 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"E:/vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/5cee/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../DanDike_NewBoard.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"E:/vivado/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_auto_pc_0_1/sim/system_auto_pc_0.v" \
    "$ref_dir/../../../bd/system/ip/system_auto_pc_7_1/sim/system_auto_pc_7.v" \
    "$ref_dir/../../../bd/system/ip/system_auto_pc_1_1/sim/system_auto_pc_1.v" \
    "$ref_dir/../../../bd/system/ip/system_auto_pc_2/sim/system_auto_pc_2.v" \
    "$ref_dir/../../../bd/system/ip/system_auto_pc_3_1/sim/system_auto_pc_3.v" \
    "$ref_dir/../../../bd/system/ip/system_auto_pc_4_1/sim/system_auto_pc_4.v" \
    "$ref_dir/../../../bd/system/ip/system_auto_pc_5/sim/system_auto_pc_5.v" \
    "$ref_dir/../../../bd/system/ip/system_auto_pc_6/sim/system_auto_pc_6.v" \
    "$ref_dir/../../../bd/system/ip/system_auto_pc_8/sim/system_auto_pc_8.v" \
    "$ref_dir/../../../bd/system/sim/system.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.system xil_defaultlib.glbl -o system_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./system_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./system.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key system_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc system_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./system.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: system.sh [-help]\n\
Usage: system.sh [-lib_map_path]\n\
Usage: system.sh [-reset_run]\n\
Usage: system.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
