# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/navigator.xdc

# Block Designs: bd/system/system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_vdma_0_0/system_axi_vdma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_vdma_0_0 || ORIG_REF_NAME==system_axi_vdma_0_0} -quiet] -quiet

# IP: bd/system/ip/system_v_tc_0_0/system_v_tc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_v_tc_0_0 || ORIG_REF_NAME==system_v_tc_0_0} -quiet] -quiet

# IP: bd/system/ip/system_v_axi4s_vid_out_0_0/system_v_axi4s_vid_out_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==system_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_0 || ORIG_REF_NAME==system_axi_gpio_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_smc_0/system_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_smc_0 || ORIG_REF_NAME==system_axi_smc_0} -quiet] -quiet

# Block Designs: bd/system/ip/system_axi_smc_0/bd_0/bd_44e3.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_0/bd_44e3_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_1/bd_44e3_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_2/bd_44e3_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_3/bd_44e3_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_4/bd_44e3_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_5/bd_44e3_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_6/bd_44e3_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_7/bd_44e3_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_8/bd_44e3_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_9/bd_44e3_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_10/bd_44e3_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_11/bd_44e3_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_12/bd_44e3_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_13/bd_44e3_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_14/bd_44e3_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_15/bd_44e3_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_16/bd_44e3_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_17/bd_44e3_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_18/bd_44e3_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_19/bd_44e3_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_20/bd_44e3_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_21/bd_44e3_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_22/bd_44e3_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_23/bd_44e3_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_24/bd_44e3_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_25/bd_44e3_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_26/bd_44e3_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_rst_ps7_0_100M_0/system_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_100M_0 || ORIG_REF_NAME==system_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/system/ip/system_ps7_0_axi_periph_0/system_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_ps7_0_axi_periph_0 || ORIG_REF_NAME==system_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_clk_wiz_0_0 || ORIG_REF_NAME==system_clk_wiz_0_0} -quiet] -quiet

# IP: bd/system/ip/system_PWM_0_0/system_PWM_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_PWM_0_0 || ORIG_REF_NAME==system_PWM_0_0} -quiet] -quiet

# IP: bd/system/ip/system_rgb2lcd_0_1/system_rgb2lcd_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rgb2lcd_0_1 || ORIG_REF_NAME==system_rgb2lcd_0_1} -quiet] -quiet

# IP: bd/system/ip/system_xlconcat_0_0/system_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_xlconcat_0_0 || ORIG_REF_NAME==system_xlconcat_0_0} -quiet] -quiet

# IP: bd/system/ip/system_xbar_0/system_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_xbar_0 || ORIG_REF_NAME==system_xbar_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_dma_0_0/system_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_dma_0_0 || ORIG_REF_NAME==system_axi_dma_0_0} -quiet] -quiet

# IP: bd/system/ip/system_adc_whole_0_0/system_adc_whole_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_adc_whole_0_0 || ORIG_REF_NAME==system_adc_whole_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axis_data_fifo_0_0/system_axis_data_fifo_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axis_data_fifo_0_0 || ORIG_REF_NAME==system_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/system/ip/system_dac_whole_0_1/system_dac_whole_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_dac_whole_0_1 || ORIG_REF_NAME==system_dac_whole_0_1} -quiet] -quiet

# IP: bd/system/ip/system_axis_data_fifo_1_1/system_axis_data_fifo_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axis_data_fifo_1_1 || ORIG_REF_NAME==system_axis_data_fifo_1_1} -quiet] -quiet

# IP: bd/system/ip/system_proc_sys_reset_0_0/system_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_proc_sys_reset_0_0 || ORIG_REF_NAME==system_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/system/ip/system_blk_mem_gen_0_0/system_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_blk_mem_gen_0_0 || ORIG_REF_NAME==system_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_bram_ctrl_0_0/system_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_bram_ctrl_0_0 || ORIG_REF_NAME==system_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/system/ip/system_onoff_config_axi_0_0/system_onoff_config_axi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_onoff_config_axi_0_0 || ORIG_REF_NAME==system_onoff_config_axi_0_0} -quiet] -quiet

# IP: bd/system/ip/system_rst_ps7_0_142M_0/system_rst_ps7_0_142M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_142M_0 || ORIG_REF_NAME==system_rst_ps7_0_142M_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_mem_intercon_0/system_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_mem_intercon_0 || ORIG_REF_NAME==system_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_0_1/system_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_1 || ORIG_REF_NAME==system_axi_gpio_0_1} -quiet] -quiet

# IP: bd/system/ip/system_axi_uartlite_0_0/system_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_uartlite_0_0 || ORIG_REF_NAME==system_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/system/ip/system_util_vector_logic_0_0/system_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_util_vector_logic_0_0 || ORIG_REF_NAME==system_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_iic_0_0/system_axi_iic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_iic_0_0 || ORIG_REF_NAME==system_axi_iic_0_0} -quiet] -quiet

# IP: bd/system/ip/system_coder_0_0/system_coder_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_coder_0_0 || ORIG_REF_NAME==system_coder_0_0} -quiet] -quiet

# IP: bd/system/ip/system_util_vector_logic_0_1/system_util_vector_logic_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_util_vector_logic_0_1 || ORIG_REF_NAME==system_util_vector_logic_0_1} -quiet] -quiet

# IP: bd/system/ip/system_power_pulse_AXI_0_0/system_power_pulse_AXI_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_power_pulse_AXI_0_0 || ORIG_REF_NAME==system_power_pulse_AXI_0_0} -quiet] -quiet

# IP: bd/system/ip/system_onoff_config_axi_0_2/system_onoff_config_axi_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_onoff_config_axi_0_2 || ORIG_REF_NAME==system_onoff_config_axi_0_2} -quiet] -quiet

# IP: bd/system/ip/system_axi_bram_ctrl_0_3/system_axi_bram_ctrl_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_bram_ctrl_0_3 || ORIG_REF_NAME==system_axi_bram_ctrl_0_3} -quiet] -quiet

# IP: bd/system/ip/system_dac_whole_0_4/system_dac_whole_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_dac_whole_0_4 || ORIG_REF_NAME==system_dac_whole_0_4} -quiet] -quiet

# IP: bd/system/ip/system_axis_data_fifo_0_3/system_axis_data_fifo_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axis_data_fifo_0_3 || ORIG_REF_NAME==system_axis_data_fifo_0_3} -quiet] -quiet

# IP: bd/system/ip/system_axis_data_fifo_1_4/system_axis_data_fifo_1_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axis_data_fifo_1_4 || ORIG_REF_NAME==system_axis_data_fifo_1_4} -quiet] -quiet

# IP: bd/system/ip/system_axi_dma_0_3/system_axi_dma_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_dma_0_3 || ORIG_REF_NAME==system_axi_dma_0_3} -quiet] -quiet

# IP: bd/system/ip/system_adc_whole_0_3/system_adc_whole_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_adc_whole_0_3 || ORIG_REF_NAME==system_adc_whole_0_3} -quiet] -quiet

# IP: bd/system/ip/system_blk_mem_gen_0_3/system_blk_mem_gen_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_blk_mem_gen_0_3 || ORIG_REF_NAME==system_blk_mem_gen_0_3} -quiet] -quiet

# IP: bd/system/ip/system_smartconnect_0_0/system_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_smartconnect_0_0 || ORIG_REF_NAME==system_smartconnect_0_0} -quiet] -quiet

# Block Designs: bd/system/ip/system_smartconnect_0_0/bd_0/bd_919a.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_0/bd_919a_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_1/bd_919a_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_2/bd_919a_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_3/bd_919a_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_4/bd_919a_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_5/bd_919a_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_6/bd_919a_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_7/bd_919a_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_8/bd_919a_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_9/bd_919a_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_10/bd_919a_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_11/bd_919a_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_12/bd_919a_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_13/bd_919a_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_14/bd_919a_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_15/bd_919a_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_16/bd_919a_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_17/bd_919a_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_18/bd_919a_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_19/bd_919a_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_20/bd_919a_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_21/bd_919a_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_22/bd_919a_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_23/bd_919a_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_24/bd_919a_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_25/bd_919a_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_26/bd_919a_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_gmii2rgmii_0_0/system_gmii2rgmii_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_gmii2rgmii_0_0 || ORIG_REF_NAME==system_gmii2rgmii_0_0} -quiet] -quiet

# IP: bd/system/ip/system_tier2_xbar_0_0/system_tier2_xbar_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_tier2_xbar_0_0 || ORIG_REF_NAME==system_tier2_xbar_0_0} -quiet] -quiet

# IP: bd/system/ip/system_tier2_xbar_1_0/system_tier2_xbar_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_tier2_xbar_1_0 || ORIG_REF_NAME==system_tier2_xbar_1_0} -quiet] -quiet

# IP: bd/system/ip/system_tier2_xbar_2_0/system_tier2_xbar_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_tier2_xbar_2_0 || ORIG_REF_NAME==system_tier2_xbar_2_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_0_1/system_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_1_1/system_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_auto_pc_1 || ORIG_REF_NAME==system_auto_pc_1} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_8/system_auto_pc_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_auto_pc_8 || ORIG_REF_NAME==system_auto_pc_8} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_2/system_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_auto_pc_2 || ORIG_REF_NAME==system_auto_pc_2} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_3_1/system_auto_pc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_auto_pc_3 || ORIG_REF_NAME==system_auto_pc_3} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_4_1/system_auto_pc_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_auto_pc_4 || ORIG_REF_NAME==system_auto_pc_4} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_5/system_auto_pc_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_auto_pc_5 || ORIG_REF_NAME==system_auto_pc_5} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_6/system_auto_pc_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_auto_pc_6 || ORIG_REF_NAME==system_auto_pc_6} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_7_1/system_auto_pc_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_auto_pc_7 || ORIG_REF_NAME==system_auto_pc_7} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_9/system_auto_pc_9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_auto_pc_9 || ORIG_REF_NAME==system_auto_pc_9} -quiet] -quiet

# XDC: bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_vdma_0_0/system_axi_vdma_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_vdma_0_0 || ORIG_REF_NAME==system_axi_vdma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_vdma_0_0/system_axi_vdma_0_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_vdma_0_0 || ORIG_REF_NAME==system_axi_vdma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_vdma_0_0/system_axi_vdma_0_0_ooc.xdc

# XDC: bd/system/ip/system_v_tc_0_0/system_v_tc_0_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_v_tc_0_0 || ORIG_REF_NAME==system_v_tc_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_v_axi4s_vid_out_0_0/system_v_axi4s_vid_out_0_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==system_v_axi4s_vid_out_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_0 || ORIG_REF_NAME==system_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0_ooc.xdc

# XDC: bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_0 || ORIG_REF_NAME==system_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_1/bd_44e3_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_1/bd_44e3_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_2/bd_44e3_arsw_0_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_3/bd_44e3_rsw_0_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_4/bd_44e3_awsw_0_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_5/bd_44e3_wsw_0_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_6/bd_44e3_bsw_0_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_10/bd_44e3_s00a2s_0_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_11/bd_44e3_sarn_0_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_12/bd_44e3_srn_0_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_16/bd_44e3_s01a2s_0_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_17/bd_44e3_sawn_0_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_18/bd_44e3_swn_0_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_19/bd_44e3_sbn_0_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_20/bd_44e3_m00s2a_0_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_21/bd_44e3_m00arn_0_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_22/bd_44e3_m00rn_0_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_23/bd_44e3_m00awn_0_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_24/bd_44e3_m00wn_0_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_0/bd_0/ip/ip_25/bd_44e3_m00bn_0_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_0/ooc.xdc

# XDC: bd/system/ip/system_rst_ps7_0_100M_0/system_rst_ps7_0_100M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_100M_0 || ORIG_REF_NAME==system_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_rst_ps7_0_100M_0/system_rst_ps7_0_100M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_100M_0 || ORIG_REF_NAME==system_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_clk_wiz_0_0 || ORIG_REF_NAME==system_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_clk_wiz_0_0 || ORIG_REF_NAME==system_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0_ooc.xdc

# XDC: bd/system/ip/system_axi_dma_0_0/system_axi_dma_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_dma_0_0 || ORIG_REF_NAME==system_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_dma_0_0/system_axi_dma_0_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_dma_0_0 || ORIG_REF_NAME==system_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_proc_sys_reset_0_0/system_proc_sys_reset_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_proc_sys_reset_0_0 || ORIG_REF_NAME==system_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_proc_sys_reset_0_0/system_proc_sys_reset_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_proc_sys_reset_0_0 || ORIG_REF_NAME==system_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_blk_mem_gen_0_0/system_blk_mem_gen_0_0_ooc.xdc

# XDC: bd/system/ip/system_rst_ps7_0_142M_0/system_rst_ps7_0_142M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_142M_0 || ORIG_REF_NAME==system_rst_ps7_0_142M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_rst_ps7_0_142M_0/system_rst_ps7_0_142M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_142M_0 || ORIG_REF_NAME==system_rst_ps7_0_142M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_gpio_0_1/system_axi_gpio_0_1_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_1 || ORIG_REF_NAME==system_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_gpio_0_1/system_axi_gpio_0_1_ooc.xdc

# XDC: bd/system/ip/system_axi_gpio_0_1/system_axi_gpio_0_1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_1 || ORIG_REF_NAME==system_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_uartlite_0_0/system_axi_uartlite_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_uartlite_0_0 || ORIG_REF_NAME==system_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_uartlite_0_0/system_axi_uartlite_0_0_ooc.xdc

# XDC: bd/system/ip/system_axi_uartlite_0_0/system_axi_uartlite_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_uartlite_0_0 || ORIG_REF_NAME==system_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_iic_0_0/system_axi_iic_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_iic_0_0 || ORIG_REF_NAME==system_axi_iic_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_iic_0_0/system_axi_iic_0_0_ooc.xdc

# XDC: bd/system/ip/system_axi_dma_0_3/system_axi_dma_0_3.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_dma_0_3 || ORIG_REF_NAME==system_axi_dma_0_3} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_dma_0_3/system_axi_dma_0_3_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_dma_0_3 || ORIG_REF_NAME==system_axi_dma_0_3} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_blk_mem_gen_0_3/system_blk_mem_gen_0_3_ooc.xdc

# XDC: bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_1/bd_919a_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_1/bd_919a_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_2/bd_919a_arsw_0_ooc.xdc

# XDC: bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_3/bd_919a_rsw_0_ooc.xdc

# XDC: bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_4/bd_919a_awsw_0_ooc.xdc

# XDC: bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_5/bd_919a_wsw_0_ooc.xdc

# XDC: bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_6/bd_919a_bsw_0_ooc.xdc

# XDC: bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_10/bd_919a_s00a2s_0_ooc.xdc

# XDC: bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_11/bd_919a_sarn_0_ooc.xdc

# XDC: bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_12/bd_919a_srn_0_ooc.xdc

# XDC: bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_16/bd_919a_s01a2s_0_ooc.xdc

# XDC: bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_17/bd_919a_sawn_0_ooc.xdc

# XDC: bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_18/bd_919a_swn_0_ooc.xdc

# XDC: bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_19/bd_919a_sbn_0_ooc.xdc

# XDC: bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_20/bd_919a_m00s2a_0_ooc.xdc

# XDC: bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_21/bd_919a_m00arn_0_ooc.xdc

# XDC: bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_22/bd_919a_m00rn_0_ooc.xdc

# XDC: bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_23/bd_919a_m00awn_0_ooc.xdc

# XDC: bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_24/bd_919a_m00wn_0_ooc.xdc

# XDC: bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_25/bd_919a_m00bn_0_ooc.xdc

# XDC: bd/system/ip/system_smartconnect_0_0/ooc.xdc

# XDC: bd/system/ip/system_auto_pc_0_1/system_auto_pc_0_ooc.xdc

# XDC: bd/system/ip/system_auto_pc_1_1/system_auto_pc_1_ooc.xdc

# XDC: bd/system/ip/system_auto_pc_8/system_auto_pc_8_ooc.xdc

# XDC: bd/system/ip/system_auto_pc_2/system_auto_pc_2_ooc.xdc

# XDC: bd/system/ip/system_auto_pc_3_1/system_auto_pc_3_ooc.xdc

# XDC: bd/system/ip/system_auto_pc_4_1/system_auto_pc_4_ooc.xdc

# XDC: bd/system/ip/system_auto_pc_5/system_auto_pc_5_ooc.xdc

# XDC: bd/system/ip/system_auto_pc_6/system_auto_pc_6_ooc.xdc

# XDC: bd/system/ip/system_auto_pc_7_1/system_auto_pc_7_ooc.xdc

# XDC: bd/system/ip/system_auto_pc_9/system_auto_pc_9_ooc.xdc

# XDC: bd/system/system_ooc.xdc
